"""Build privacy_comps.js (loaded by index.html) from privacy_comps.json.

privacy_comps.json is the hand-editable source for the "Privacy Wiretap Comps" tab:
researched class settlements pleading CIPA 631/632, the federal Wiretap Act (ECPA)
or Florida's FSCA. It is kept apart from settlements.json so the 6-hourly refresh
bot never touches it. Edit the JSON, then run:

    python build_privacy_comps.py
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "privacy_comps.json")
OUT = os.path.join(ROOT, "privacy_comps.js")

STATUTE_KEYS = ["cipa_631", "cipa_632", "cipa_632_7", "cipa_638_51", "ecpa_wiretap", "fsca"]
TARGET_KEYS = ["cipa_631", "cipa_632", "ecpa_wiretap", "fsca"]
STATUSES = {"Final approval", "Preliminary approval", "Prelim motion pending"}


def validate(data):
    problems = []
    for i, r in enumerate(data.get("rows", [])):
        name = r.get("short_name") or "row %d" % i
        for k in STATUTE_KEYS:
            if r.get(k) not in ("pled", "not_pled", "unknown"):
                problems.append("%s: %s must be pled / not_pled / unknown" % (name, k))
        if not any(r.get(k) == "pled" for k in TARGET_KEYS):
            problems.append("%s: pleads none of 631 / 632 / ECPA / FSCA" % name)
        if r.get("status") not in STATUSES:
            problems.append("%s: unexpected status %r" % (name, r.get("status")))
        if not r.get("sources"):
            problems.append("%s: no sources" % name)
    return problems


def main():
    with open(SRC, encoding="utf-8") as f:
        data = json.load(f)
    problems = validate(data)
    if problems:
        print("privacy_comps.json has problems:\n  " + "\n  ".join(problems))
        sys.exit(1)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by build_privacy_comps.py from privacy_comps.json -- do not edit. */\n")
        f.write("window.PRIVACY_COMPS = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print("Wrote %d settlements (%d screened out) to privacy_comps.js"
          % (len(data.get("rows", [])), len(data.get("screened_out", []))))


if __name__ == "__main__":
    main()
