#!/usr/bin/env python3
"""Consolidate all AI Watchdog screener results into one formatted Excel workbook."""
import csv, os, sys
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from datasets_config import MODES

OUT = sys.argv[1] if len(sys.argv) > 1 else "AI_Watchdog_Report.xlsx"
HDR_FILL = PatternFill("solid", fgColor="1F3864")
HDR_FONT = Font(bold=True, color="FFFFFF", size=11)
TITLE_FONT = Font(bold=True, size=16, color="1F3864")
SUB_FONT = Font(bold=True, size=12, color="1F3864")
WRAP = Alignment(wrap_text=True, vertical="top")
THIN = Border(*[Side(style="thin", color="D9D9D9")] * 4)
FLAG_FILL = {
    "USED_BY": PatternFill("solid", fgColor="F4CCCC"),          # red-ish
    "DOWNLOADED_ONLY": PatternFill("solid", fgColor="FCE5CD"),  # orange-ish
    "PRESENT": PatternFill("solid", fgColor="FFF2CC"),          # yellow-ish
    "ASSEMBLED_ONLY": PatternFill("solid", fgColor="FFF2CC"),
    "NONE": PatternFill("solid", fgColor="EFEFEF"),
    "STRONG": PatternFill("solid", fgColor="F4CCCC"),
    "MODERATE": PatternFill("solid", fgColor="FCE5CD"),
    "WEAK (incidental)": PatternFill("solid", fgColor="EFEFEF"),
}


def style_header(ws, ncols, row=1):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = HDR_FILL; cell.font = HDR_FONT
        cell.alignment = Alignment(vertical="center", wrap_text=True)
    ws.freeze_panes = ws.cell(row=row + 1, column=1)
    ws.auto_filter.ref = f"A{row}:{get_column_letter(ncols)}{row}"
    ws.row_dimensions[row].height = 28


def autosize(ws, maxw=60, ncols=None):
    ncols = ncols or ws.max_column
    for c in range(1, ncols + 1):
        letter = get_column_letter(c)
        longest = 0
        for cell in ws[letter]:
            if cell.value is not None:
                longest = max(longest, len(str(cell.value)))
        ws.column_dimensions[letter].width = min(max(longest + 2, 10), maxw)


def sheet_from_csv(wb, title, path, flag_col=None, limit=None, sortkey=None):
    if not os.path.exists(path):
        return None
    rows = list(csv.reader(open(path, encoding="utf-8")))
    if not rows:
        return None
    header, body = rows[0], rows[1:]
    if sortkey is not None:
        try:
            body.sort(key=lambda r: -float(r[sortkey] or 0))
        except Exception:
            pass
    if limit:
        body = body[:limit]
    ws = wb.create_sheet(title)
    ws.append(header)
    flag_idx = header.index(flag_col) if (flag_col and flag_col in header) else None
    for r in body:
        ws.append(r)
        if flag_idx is not None:
            fill = FLAG_FILL.get(r[flag_idx])
            if fill:
                ws.cell(row=ws.max_row, column=flag_idx + 1).fill = fill
    style_header(ws, len(header))
    autosize(ws, ncols=len(header))
    return ws


def main():
    wb = openpyxl.Workbook()

    # ---- Overview ----
    ov = wb.active; ov.title = "Overview"
    ov.column_dimensions["A"].width = 110
    lines = [
        ("The Atlantic 'AI Watchdog' — Screener Results", "title"),
        ("Generated by atlantic_ai_watchdog/ — screens artists & YouTube creators against The Atlantic's", None),
        ("AI Watchdog tool to flag those whose work is in a dataset an AI company used to train models.", None),
        ("", None),
        ("KEY FINDING", "sub"),
        ("• MUSIC: only 1 of 4 datasets is 'used by' a company — Free Music Archive (Google + Stability AI).", None),
        ("  FMA is Creative-Commons music that FORBIDS commercial use, yet was used to train commercial AI.", None),
        ("  Mainstream/top artists barely appear in FMA; the real targets are indie/CC artists (17,665 of them).", None),
        ("• VIDEO: 7 of 11 datasets are 'used by' named companies (Meta, Nvidia, ByteDance, Amazon, Runway, etc.).", None),
        ("", None),
        ("SHEETS", "sub"),
        ("• CLIENTS — Music Used by LLMs — THE outreach list: 17,665 musicians whose tracks are in", None),
        ("  Free Music Archive (used by Google & Stability AI). Ranked by tracks_used; STRONG = 25+ tracks,", None),
        ("  MODERATE = 5-24, WEAK = 1 incidental track. 17,608 have a MusicBrainz id for identification.", None),
        ("• Dataset Classification — every dataset, its flag, and which companies used it.", None),
        ("• Music — FMA Targets — the full 17,665 USED_BY music artists (Google + Stability AI).", None),
        ("• Music — Top FMA Enriched — top 702 FMA artists with their counts across all music datasets.", None),
        ("• Music — Mainstream 2126 — top mainstream artists (mostly present/downloaded, few USED_BY).", None),
        ("• Video — Runway Channels — YouTube channels in Runway's Gen-3 training set (if harvested).", None),
        ("", None),
        ("FLAG MEANINGS", "sub"),
        ("USED_BY = in a dataset a named AI company used to train/experiment (strongest signal).", None),
        ("DOWNLOADED_ONLY = dataset widely downloaded, no company named.  PRESENT/ASSEMBLED_ONLY = in a", None),
        ("training set but no usage/download claim.  NONE = not found in any dataset.", None),
        ("", None),
        ("CAVEAT: 'present in a dataset' is not proof a specific model trained on a specific work; it reflects", None),
        ("what The Atlantic's AI Watchdog documents. Verify each flagged target before acting.", None),
    ]
    for text, kind in lines:
        ov.append([text])
        cell = ov.cell(row=ov.max_row, column=1)
        if kind == "title": cell.font = TITLE_FONT
        elif kind == "sub": cell.font = SUB_FONT
        cell.alignment = WRAP

    # ---- CLIENTS (headline tabs — strict USED_BY only) ----
    sheet_from_csv(wb, "CLIENTS — Music Used by LLMs", "music_clients_used_by_llms.csv",
                   flag_col="strength")
    sheet_from_csv(wb, "CLIENTS — Video (Used By)", "video_channels_flagged.csv",
                   flag_col="flag", sortkey=3)     # only channels in a used-by dataset
    sheet_from_csv(wb, "CLIENTS — Jewish (Used By)", "jewish_flagged.csv",
                   flag_col="flag", sortkey=3)     # only Jewish artists in a used-by dataset

    # ---- Dataset Classification ----
    cls = wb.create_sheet("Dataset Classification")
    cls.append(["Mode", "Dataset", "Flag", "Used by (companies)",
                "Exact wording (The Atlantic)", "Article URL"])
    for mode in ("music", "video"):
        cfg = MODES[mode]
        for slug in cfg["datasets"]:
            st = cfg["status"].get(slug, "UNKNOWN")
            flag = {"USED_BY": "USED_BY", "DOWNLOADED_ONLY": "DOWNLOADED_ONLY",
                    "ASSEMBLED_ONLY": "assembled-only", "UNKNOWN": "unknown"}.get(st, st)
            cls.append([mode, slug, flag,
                        ", ".join(cfg.get("used_by", {}).get(slug, [])),
                        cfg.get("wording", {}).get(slug, ""),
                        cfg.get("article", {}).get(slug, "")])
            if st == "USED_BY":
                cls.cell(row=cls.max_row, column=3).fill = FLAG_FILL["USED_BY"]
            cls.cell(row=cls.max_row, column=5).alignment = WRAP
    style_header(cls, 6); autosize(cls, ncols=6)
    cls.column_dimensions["E"].width = 90   # wording column: wide + wrapped

    # ---- Data sheets ----
    sheet_from_csv(wb, "Music — FMA Targets", "music_fma_used_by_targets.csv", flag_col="flag")
    sheet_from_csv(wb, "Clients — Jewish Musicians", "jewish_results.csv", flag_col="flag",
                   sortkey=3)  # total_results (Wikipedia-category based; approximate)
    sheet_from_csv(wb, "Music — FMA Clients Enriched", "fma_clients_results.csv", flag_col="flag",
                   sortkey=4)  # count__free-music-archive
    sheet_from_csv(wb, "Music — Recognizable 2126", "music_top_results.csv", flag_col="flag",
                   sortkey=3)  # total_results
    sheet_from_csv(wb, "Video — Channels Screened", "video_channels_results.csv", flag_col="flag",
                   sortkey=3)  # total_results across all 11 video datasets
    sheet_from_csv(wb, "Video — Runway Channel List", "video_runway_targets.csv", flag_col="flag",
                   sortkey=2)  # runway_clip_count

    wb.save(OUT)
    print("wrote", OUT, "with sheets:", ", ".join(s.title for s in wb.worksheets))


if __name__ == "__main__":
    main()
